### ISSUE TITLE
can't convert String into an exact number

### ISSUE THREAD

**Issue by tiredpixel** [tiredpixel/sidekiq-spy#12]
Attempting to use the `--namespace` option with ruby 2.1.1, sidekiq 2.17.7 errors with

```
/Users/tp2/.rbenv/versions/2.1.1/bin/sidekiq-spy: can't convert String into an exact number
```

Running with `--debug` shows

```
/Users/tp2/.rbenv/versions/2.1.1/bin/sidekiq-spy: can't convert String into an exact number
/Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.7/lib/sidekiq/api.rb:430:in `at': can't convert String into an exact number (TypeError)
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.7/lib/sidekiq/api.rb:430:in `block (2 levels) in each'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.7/lib/sidekiq/api.rb:426:in `each'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.7/lib/sidekiq/api.rb:426:in `block in each'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/connection_pool-2.0.0/lib/connection_pool.rb:58:in `with'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.7/lib/sidekiq.rb:67:in `redis'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-2.17.7/lib/sidekiq/api.rb:424:in `each'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-spy-0.3.2/lib/sidekiq-spy/spy/workers.rb:20:in `refresh'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-spy-0.3.2/lib/sidekiq-spy/spy/workers.rb:14:in `initialize'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-spy-0.3.2/lib/sidekiq-spy/display/panels/workers.rb:9:in `new'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-spy-0.3.2/lib/sidekiq-spy/display/panels/workers.rb:9:in `initialize'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-spy-0.3.2/lib/sidekiq-spy/display/screen.rb:67:in `new'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-spy-0.3.2/lib/sidekiq-spy/display/screen.rb:67:in `panel_main='
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-spy-0.3.2/lib/sidekiq-spy/display/screen.rb:29:in `initialize'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-spy-0.3.2/lib/sidekiq-spy/app.rb:86:in `new'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-spy-0.3.2/lib/sidekiq-spy/app.rb:86:in `setup'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-spy-0.3.2/lib/sidekiq-spy/app.rb:30:in `start'
  from /Users/tp2/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sidekiq-spy-0.3.2/bin/sidekiq-spy:115:in `<top (required)>'
  from /Users/tp2/.rbenv/versions/2.1.1/bin/sidekiq-spy:23:in `load'
  from /Users/tp2/.rbenv/versions/2.1.1/bin/sidekiq-spy:23:in `<main>'
```

**Comment by tiredpixel** [comment]
This project is EOL. Closing.
